### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by GMatrixGames** [lucko/PunishmentGui#1]
Hello @lucko,
I was looking through your repositories, and I saw this one.
I was wondering, will this/was this released on SpigotMC/a plugin downloading platform.
If so, can you link me it because I would love to download this.
Thanks,
GMatrixGames

**Comment by lucko** [comment]
You can download a copy here.

https://ci.lucko.me/job/PunishmentGui/

It also depends on `helper.jar` and `helper-sql.jar` from here: https://ci.lucko.me/job/helper/

**Comment by lucko** [comment]
And uh, I wasn't planning on releasing it.

I made it for a private project, but in my free time, so decided to post it publicly on GH so people could have a poke around. :)

**Comment by GMatrixGames** [comment]
Thanks! Just saw it and was interested!

________________________________

GMatrix Games
https://goo.gl/Tsiiia


________________________________
